version: "3.5"
services:
  go-backend-course:
    platform: linux/amd64
    container_name: go-backend-course
    build: 
      context: ./.dockers/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_backend_course
    ports:
      - "3322:3306"
    volumes:
      - ./.dockers/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql